import 'package:flutter/material.dart';

/// Centralized localized strings for English and Tagalog translations
class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'report_issue_title': 'Report Issue',
      'outage_map_title': 'Outage Map',
      'community_feed_title': 'Community Feed',
      'profile_title': 'Profile',
      'submit_report_button': 'Submit Report',
      'sign_out': 'Sign Out',
      'sign_out_confirmation': 'Are you sure you want to sign out?',
      'cancel': 'Cancel',
      'account_information': 'Account Information',
      'barangay_label': 'Barangay:',
      'mobile_label': 'Mobile:',
      'reports_submitted_label': 'Reports Submitted:',
      'language_label': 'Language / Wika',
      // Nav
      'nav_report': 'Report',
      'nav_map': 'Map',
      'nav_feed': 'Feed',
      'nav_profile': 'Profile',
      // Report Screen
      'report_form_barangay': 'Barangay',
      'report_form_barangay_hint': 'Select your barangay',
      'report_form_issue_type': 'Issue Type',
      'report_form_notes': 'Additional Notes (Optional)',
      'report_form_notes_hint': 'Describe the issue in more detail...',
      'report_form_autofilled': 'Auto-filled Information',
      'report_location_not_set': 'Location not set',
      'report_snackbar_missing_fields': 'Please fill in all required fields',
      'report_snackbar_success': 'Report submitted successfully!',
      'report_issue_blackout': 'Total Blackout',
      'report_issue_blackout_desc': 'Complete power outage',
      'report_issue_low_voltage': 'Low Voltage',
      'report_issue_low_voltage_desc': 'Dim lights, weak appliances',
      'report_issue_flickering': 'Flickering Lights',
      'report_issue_flickering_desc': 'Unstable power supply',
      // Feed
      'feed_search_hint': 'Search by barangay or issue...',
      'feed_no_reports': 'No reports yet.',
      'status_pending': 'Pending',
      'status_acknowledged': 'Acknowledged',
      'status_resolved': 'Resolved',
      'time_just_now': 'Just now',
      'time_m_ago': 'm ago',
      'time_h_ago': 'h ago',
      'time_d_ago': 'd ago',
      // Map
      'map_legend_blackout': 'Blackout',
      'map_legend_low_voltage': 'Low Voltage',
      'map_legend_flickering': 'Flickering',
      'map_notes': 'Notes:',
      // Admin Dashboard
      'admin_title': 'Command Center',
      'admin_active': 'Active',
      'admin_fixed': 'Fixed',
      'admin_pending_issues': 'Pending Issues',
      'admin_all_reports': 'All Reports',
      'admin_no_reports': 'No reports for',
      'admin_dispatch': 'Dispatch',
      'admin_resolve': 'Resolve',
      'error_prefix': 'Error:',
      'error_retry': 'Retry',
      'error_offline': 'No Internet Connection',
      // Feed Screen
      'feed_all_status': 'All Status',
      // Onboarding Screen
      'onboarding_skip': 'Skip',
      'onboarding_title_1': 'Report Issues',
      'onboarding_desc_1': 'Easily report power outages in your area.',
      'onboarding_title_2': 'Track Outages',
      'onboarding_desc_2': 'View real-time map of affected barangays.',
      'onboarding_title_3': 'Stay Updated',
      'onboarding_desc_3': 'Get community updates and status changes.',
      'onboarding_get_started': 'Get Started',
      'onboarding_next': 'Next',
      // Profile Screen
      'profile_not_logged_in': 'Not logged in',
      'profile_error': 'Something went wrong',
      // Report Screen
      'report_queued_offline': 'Report queued (offline). Will send when online.',
      'report_unknown_error': 'Unknown error',
      'report_error_profanity': 'Please remove inappropriate language from your report.',
    },
    'tl': {
      'report_issue_title': 'Iulat ang Problema',
      'outage_map_title': 'Mapa ng Brownout',
      'community_feed_title': 'Kuwentong Komunidad',
      'profile_title': 'Aking Profile',
      'submit_report_button': 'Ipadala ang Ulat',
      'sign_out': 'Mag-logout',
      'sign_out_confirmation': 'Sigurado ka bang gusto mong mag-logout?',
      'cancel': 'Kanselahin',
      'account_information': 'Impormasyon ng Account',
      'barangay_label': 'Barangay:',
      'mobile_label': 'Mobile:',
      'reports_submitted_label': 'Naipadalang Ulat:',
      'language_label': 'Wika / Language',
      // Nav
      'nav_report': 'Iulat',
      'nav_map': 'Mapa',
      'nav_feed': 'Feed',
      'nav_profile': 'Profile',
      // Report Screen
      'report_form_barangay': 'Barangay',
      'report_form_barangay_hint': 'Piliin ang iyong barangay',
      'report_form_issue_type': 'Uri ng Problema',
      'report_form_notes': 'Karagdagang Tala (Opsyonal)',
      'report_form_notes_hint': 'Ilarawan ang problema...',
      'report_form_autofilled': 'Auto-filled na Impormasyon',
      'report_location_not_set': 'Walang lokasyon',
      'report_snackbar_missing_fields': 'Punan ang lahat ng kailangang field',
      'report_snackbar_success': 'Matagumpay na naipadala ang ulat!',
      'report_issue_blackout': 'Total Blackout',
      'report_issue_blackout_desc': 'Walang kuryente',
      'report_issue_low_voltage': 'Low Voltage',
      'report_issue_low_voltage_desc': 'Mahina ang ilaw, mahina ang appliances',
      'report_issue_flickering': 'Flickering Lights',
      'report_issue_flickering_desc': 'Patay-sindi ang kuryente',
      // Feed
      'feed_search_hint': 'Maghanap sa barangay o problema...',
      'feed_no_reports': 'Wala pang ulat.',
      'status_pending': 'Pending',
      'status_acknowledged': 'Tinanggap',
      'status_resolved': 'Naayos na',
      'time_just_now': 'Ngayon lang',
      'time_m_ago': 'm nakalipas',
      'time_h_ago': 'h nakalipas',
      'time_d_ago': 'araw nakalipas',
      // Map
      'map_legend_blackout': 'Blackout',
      'map_legend_low_voltage': 'Low Voltage',
      'map_legend_flickering': 'Flickering',
      'map_notes': 'Tala:',
      // Admin Dashboard
      'admin_title': 'Sentrong Pangangasiwa',
      'admin_active': 'Aktibo',
      'admin_fixed': 'Ayos Na',
      'admin_pending_issues': 'Mga Pending',
      'admin_all_reports': 'Lahat ng Ulat',
      'admin_no_reports': 'Walang ulat para sa',
      'admin_dispatch': 'Ipadala',
      'admin_resolve': 'Ayusin',
      'error_prefix': 'Error:',
      'error_retry': 'Ulitin',
      'error_offline': 'Walang Internet Connection',
      // Feed Screen
      'feed_all_status': 'Lahat ng Status',
      // Onboarding Screen
      'onboarding_skip': 'Laktawan',
      'onboarding_title_1': 'Mag-ulat ng Problema',
      'onboarding_desc_1': 'Madaling mag-ulat ng brownout sa inyong lugar.',
      'onboarding_title_2': 'Sundan ang mga Brownout',
      'onboarding_desc_2': 'Tingnan ang real-time na mapa ng mga apektadong barangay.',
      'onboarding_title_3': 'Maging Update',
      'onboarding_desc_3': 'Makakuha ng mga update mula sa komunidad.',
      'onboarding_get_started': 'Magsimula',
      'onboarding_next': 'Susunod',
      // Profile Screen
      'profile_not_logged_in': 'Hindi naka-log in',
      'profile_error': 'May nangyaring mali',
      // Report Screen
      'report_queued_offline': 'Naka-queue ang ulat (offline). Ipadadala kapag online na.',
      'report_unknown_error': 'Hindi malamang error',
      'report_error_profanity': 'Pakialis ang mga hindi angkop na salita sa iyong ulat.',
    },
  };

  static String tr(String key, Locale locale) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}
